### PR TITLE
Merge oet_main into main

### PR DESCRIPTION
**Pull request by finozzifa**
# Closes # (if applicable).

## Changes proposed in this Pull Request

This Pull Request merges _oet_main_ into _main_

## Checklist

- [x] I consent to the release of this PR's code under the AGPLv3 license and non-code contributions under CC0-1.0 and CC-BY-4.0.
- [x] I tested my contribution locally and it seems to work fine.
- [ ] Code and workflow changes are sufficiently documented.
- [ ] Newly introduced dependencies are added to `envs/environment.yaml` and `doc/requirements.txt`.
- [ ] Changes in configuration options are added in all of `config.default.yaml` and `config.tutorial.yaml`.
- [ ] Add a test config or line additions to `test/` (note tests are changing the config.tutorial.yaml)
- [ ] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [ ] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

### CODE REVIEW

**Review by FabianHofmann — COMMENTED** [review]
looks good, was the latest state of the main in sync with the upstream?

**Comment by finozzifa** [comment]
Hi @FabianHofmann , thanks for your comment. Indeed both branches were up to date with upstream. If you agree I would squash merge.

**Comment by FabianHofmann** [comment]
mmh, I am just thinking whether squashing is the right thing to do. because then we can only carry over the whole pr to the upstream. so perhaps ordinary merge for now?

**Comment by finozzifa** [comment]
ja I agree with you. Standard merge then!

**Pull request merged**
